language: node_js
node_js:
  - "12.13"

jobs:
  include:
    - stage: lintAndTest
      - npm run lint
    - stage: npm release
      if: branch = master
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_AUTH_TOKEN"
